[package]
name = "assistant"
version = "0.1.0"
edition = "2021"

[dependencies]
carapax = { version = "0.12.0", features = ["access", "dialogue", "session-redis"] }
dotenv = "0.15.0"
env_logger = "0.9.0"
log = "0.4.14"
redis = { version = "0.21.5", features = ["aio", "connection-manager", "tokio-comp"] }
serde = "1.0.136"
serde_yaml = "0.8.23"
tokio = { version = "1.16.1", features = ["macros", "rt-multi-thread"] }
