[package]
name = "assistant"
version = "0.1.0"
edition = "2021"

[dependencies]
barrel = { version = "0.7.0", features = ["pg"] }
carapax = { version = "0.12.0", features = ["access", "dialogue", "session-redis"] }
clap = { version = "4.0.32", features = ["derive"] }
dotenv = "0.15.0"
env_logger = "0.10.0"
log = "0.4.14"
redis = { version = "0.21.5", features = ["aio", "connection-manager", "tokio-comp"] }
refinery = { version = "0.8.4", features = ["tokio-postgres"] }
serde = "1.0.136"
serde_json = "1.0.79"
serde_yaml = "0.9.16"
tokio = { version = "1.16.1", features = ["macros", "rt-multi-thread"] }
tokio-postgres = { version = "0.7.5", features = ["with-serde_json-1"] }
